FROM python:3-alpine

EXPOSE 5000

RUN mkdir /app
WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY requirements.test.txt /app/requirements.test.txt
RUN pip install -r requirements.test.txt

COPY . /app

CMD pytest
